spring:
  profiles: default

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
      access-token-uri: http://localhost:8095/oauth/token
      user-authorization-uri: http://localhost:8095/oauth/authorize
      registered-redirect-uri: http://localhost:8095/hello
    resource: 
      jwt:
        key-value: helloworld

---
spring:
  profiles: dev

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
      access-token-uri: http://${auth.host}:8095/oauth/token
      user-authorization-uri: http://${auth.host}:8095/oauth/authorize
    resource: 
      jwt:
        key-value: helloworld


        