spring:
  profiles: default

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource: 
      jwt:
        key-value: helloworld

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  profiles: dev

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource: 
      jwt:
        key-value: helloworld


        