spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${mysql.connection.uri:jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}'
    username: root
    password: '${mysql.root.password:asdf1234}'

eureka:
  instance:
    hostname: ${hostname}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://${hostname}:8761/eureka/

debug: true
