msaconfig:
  greeting: "hello"

---

spring:
  profiles: local

msaconfig:
  greeting: "welcome to local server"

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.connection.uri:jdbc:mysql://localhost:3306/order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: root
    password: ${mysql.root.password:asdf1234}

eureka:
  client:
    serviceUrl:
      defaultZone: '${eureka.server:http://localhost:8761/eureka/}'

debug: true


---
spring:
  profiles: test

msaconfig:
  greeting: "welcome to test server"

---
spring:
  profiles: staging

msaconfig:
  greeting: "welcome to staging server"

---
spring:
  profiles: prod
  
msaconfig:
  greeting: "welcome to prod server"