spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${mysql.connection.uri:jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}'
    username: root
    password: '${mysql.root.password:asdf1234}'

eureka:
  client:
    serviceUrl:
      defaultZone: '${eureka.server:http://localhost:8761/eureka/}'

debug: true
