msaconfig:
  greeting: "hello"
  
---

spring:
  profiles: local

msaconfig:
  greeting: "welcome to local server"

---

spring:
  profiles: dev

msaconfig:
  greeting: "welcome to dev server"

---

spring:
  profiles: test
  
msaconfig:
  greeting: "welcome to test server"

---

spring:
  profiles: staging
  
msaconfig:
  greeting: "welcome to staging server"

---

spring:
  profiles: prod
  
msaconfig:
  greeting: "welcome to prod server"