spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${database.name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: '${mysql.root.password:asdf1234}'

mybatis:
  type-aliases-package: com.js.${package.name}.dto
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/${database.name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: asdf1234

mybatis:
  type-aliases-package: com.js.${package.name}.dto
  mapper-locations: classpath:mapper/*.xml
    
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-0.mysql.default.svc.cluster.local:3306/${database.name}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: '${mysql.root.password:asdf1234}'

mybatis:
  type-aliases-package: com.js.${package.name}.dto
  mapper-locations: classpath:mapper/*.xml