eureka:
  instance:
    hostname: '${HOSTNAME}.eureka'
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: '${EUREKA_CLUSTER_SERVICES}'

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh","info"]