eureka:
  instance:
    hostname: ${hostname}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://${hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh","info"]