zuul:
  routes:
    wcafe-web:
      path: /web/**
    wcafe-order:
      path: /api/order/**
    wcafe-product:
      path: /api/product/**
    wcafe-auth-server:
    path: /auth/**
  sensitiveHeaders: Cookie, Set-Cookie