zuul:
  # true인 경우, X-Forwarded-* 헤더가 추가됨
  add-proxy-headers: false
  sensitiveHeaders: Cookie,Set-Cookie 

  # NOTE : Zuul 라우팅 목록 중 "kthcorp-example"를 제외하고 ignore 한다.
  ignored-services: '*'
  host:
    max-total-connections: 500
  ribbon-isolation-strategy: THREAD
  routes:
    routes:
    wcafe-order:
      path: /api/order/**
    wcafe-product:
      path: /api/product/**
    wcafe-user:
      path: /api/user/**
      
  thread-pool:
    use-separate-thread-pools: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 40000

  # 참조 : https://github.com/Netflix/Hystrix/wiki/configuration#threadpool-properties
  # ribbon-isolation-strategy을 THREAD로 설정한 경우 "ThreadPoolExecutor" Size 설정.
  threadpool:
    default:
      coreSize: 50
      maximumSize: 500
      keepAliveTimeMinutes: 1
      # "allowMaximumSizeToDivergeFromCoreSize"가 설정 된 경우에만 "maximumSize"값이 적용됨.
      allowMaximumSizeToDivergeFromCoreSize: true
    spring-cloud-msa-webapp01:
      coreSize: 50
      maximumSize: 500
      keepAliveTimeMinutes: 1
      # "allowMaximumSizeToDivergeFromCoreSize"가 설정 된 경우에만 "maximumSize"값이 적용됨.
      allowMaximumSizeToDivergeFromCoreSize: true
    spring-cloud-msa-webapp02:
      coreSize: 50
      maximumSize: 500
      keepAliveTimeMinutes: 1
      # "allowMaximumSizeToDivergeFromCoreSize"가 설정 된 경우에만 "maximumSize"값이 적용됨.
      allowMaximumSizeToDivergeFromCoreSize: true

ribbon:
  # --------------------------------------------------------------------------------
  # Ribbon read and connect timeout 계산.
  # ribbonTimeout = (ConnectTimeout + ReadTimeout) * (MaxAutoRetries + 1) * (MaxAutoRetriesNextServer + 1);
  # Hystrix의 timeoutInMilliseconds 시간은 위의 계산 값보다 크게 설정.
  # --------------------------------------------------------------------------------
  # Read timeout used by Apache HttpClient (Default. 1000)
  ReadTimeout: 5000

  # Connect timeout used by Apache HttpClient (Default. 1000)
  ConnectTimeout: 5000

  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule


client-url: http://${client-host:localhost}:8080