zuul:
  routes:
    wcafe-web:
      path: /web/**
    wcafe-order:
      path: /api/order/**
    wcafe-product:
      path: /api/product/**
    wcafe-user:
      path: /api/user/**
  sensitiveHeaders: Cookie, Set-Cookie